# @package _global_

defaults:
  - /model/mlp_small_score
  - /model/mlp_small_potential

ranged_models:
  - _target_: scoremd.models.RangedModel
    model: ${model.mlp_small_score}
    range: [1.0, 0.6]
  - _target_: scoremd.models.RangedModel
    model: ${model.mlp_small_score}
    range: [0.6, 0.1]
  - _target_: scoremd.models.RangedModel
    model: ${model.mlp_small_potential}
    range: [0.1, 0]
