# @package _global_

defaults:
  - /model/transformer_large_score
  - /model/transformer_large_potential

ranged_models:
  - _target_: scoremd.models.RangedModel
    model: ${model.transformer_large_score}
    range: [1.0, 0.6]
  - _target_: scoremd.models.RangedModel
    model: ${model.transformer_large_score}
    range: [0.6, 0.1]
  - _target_: scoremd.models.RangedModel
    model: ${model.transformer_large_potential}
    range: [0.1, 0.0]
