# @package _global_

defaults:
  - /model/transformer_potential_like_three

ranged_models:
  - _target_: scoremd.models.RangedModel
    model: ${model.transformer_potential_like_three}
    range: [1.0, 0.0]
